name: Update Docker Site

on:
  push:
    branches:
      - main

jobs:
  update-site:
    runs-on: self-hosted

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Update Docker Site
        run: |
          cd ~/docker/9cps-kupe-house-site/data
          sudo git pull
